create table employee
(
    id     int generated by default as identity primary key,
    name   varchar(30) not null,
    age    int,
    salary float4
);
insert into employee (name, age, salary)
values ('Bob', 20, 1000),
       ('Pipa', 25, 5000),
       ('Booboo',99, 200);