create table user
(
    id       int generated by default as identity primary key ,
    username varchar(30) not null,
    age      int check ( age > 0 ),
    email    varchar(100) unique
);

create table item
(
    id        int generated by default as identity primary key ,
    item_name varchar(50) not null,
    price float check ( price>0 )
);
create  table orders(
    id int generated by default as identity primary key ,
    user_id int references user(id),
    item_id int references  item(id)
)